backend:
  replicaCount: 2
  responseMessage: "Hello from DevOps Shop Backend - DEV"

frontend:
  replicaCount: 1
  responseMessage: "DevOps Shop Frontend - DEV"

redis:
  enabled: true

  haMode:
    enabled: true

  metrics:
    enabled: false