apiVersion: v1
kind: ConfigMap

metadata:
  name: frontend-nginx-config
  namespace: devops-shop

data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 8080;
        
        location / {
          default_type text/plain;
          return 200 "DevOps Shop Frontend\n";
          }
          
          location /api/ {
            proxy_pass http://backend/;
          }
        }
      }